# Generated by Django 5.1.5 on 2025-02-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='学生编号')),
                ('student_name', models.CharField(max_length=50, verbose_name='学生姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10, verbose_name='性别')),
                ('school', models.CharField(max_length=100, verbose_name='学校')),
                ('phone_number', models.CharField(max_length=11, verbose_name='手机号码')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='教师编号')),
                ('teacher_name', models.CharField(max_length=50, verbose_name='教师姓名')),
                ('school', models.CharField(max_length=100, verbose_name='学校/单位')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10, verbose_name='性别')),
                ('phone_number', models.CharField(max_length=11, verbose_name='手机号码')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮箱')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
