# Generated by Django 5.1.5 on 2025-03-03 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False, verbose_name='资料编号')),
                ('material_name', models.CharField(max_length=100, verbose_name='资料名称')),
                ('material_file', models.FileField(upload_to='course_materials/', verbose_name='课程资料')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manage.course', verbose_name='课程编号')),
            ],
            options={
                'db_table': 'material',
            },
        ),
    ]
