# Generated by Django 5.1.5 on 2025-03-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.CharField(blank=True, choices=[('doc', 'Word 文档'), ('pdf', 'PDF 文档'), ('ppt', 'PPT 幻灯片'), ('mp4', '视频文件'), ('jpg', '图片文件'), ('other', '其他')], max_length=10),
        ),
    ]
