# Generated by Django 5.1.5 on 2025-03-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0002_material_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核不通过')], default='pending', max_length=10, verbose_name='审核状态'),
        ),
    ]
