# Generated by Django 5.1.5 on 2025-03-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0003_material_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_name',
            field=models.CharField(max_length=200, verbose_name='资料名称'),
        ),
    ]
