# Generated by Django 5.1.5 on 2025-03-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0004_alter_material_material_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='status',
            new_name='review_status',
        ),
    ]
