# Generated by Django 5.1.5 on 2025-03-17 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manage', '0003_learningrecord_material_id'),
        ('course_material', '0005_rename_status_material_review_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False, verbose_name='资料编号')),
                ('video_name', models.CharField(max_length=200, verbose_name='资料名称')),
                ('video_file', models.FileField(upload_to='course_video/', verbose_name='课程视频')),
                ('review_status', models.CharField(choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核不通过')], default='pending', max_length=10, verbose_name='审核状态')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manage.course', verbose_name='课程编号')),
            ],
            options={
                'db_table': 'video',
            },
        ),
    ]
