# Generated by Django 5.1.5 on 2025-03-23 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manage', '0004_learningrecord_video_id_chapter'),
        ('course_material', '0006_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='chapter_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_manage.chapter', verbose_name='章节编号'),
        ),
    ]
