# Generated by Django 5.1.5 on 2025-03-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0007_video_chapter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_duration',
            field=models.FloatField(blank=True, null=True, verbose_name='视频时长（分钟）'),
        ),
    ]
