# Generated by Django 5.1.5 on 2025-03-31 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_manage', '0006_learningrecord_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论编号')),
                ('user_id', models.CharField(max_length=20, verbose_name='用户编号')),
                ('user_role', models.CharField(max_length=10, verbose_name='用户角色')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manage.course', verbose_name='课程编号')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='interact.comment', verbose_name='父评论')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
