# Generated by Django 5.1.5 on 2025-03-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_role',
            field=models.CharField(max_length=100, verbose_name='用户角色'),
        ),
    ]
