# Generated by Django 5.1.5 on 2025-04-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0002_alter_comment_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.CharField(default='默认话题', max_length=100, verbose_name='话题'),
        ),
    ]
