# Generated by Django 5.1.5 on 2025-04-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0003_comment_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='被回复者用户ID'),
        ),
    ]
