# Generated by Django 5.1.5 on 2025-03-03 08:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='课程编号')),
                ('course_name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('course_cover', models.ImageField(null=True, upload_to='course_covers/', verbose_name='课程封面')),
                ('course_intro', models.TextField(verbose_name='课程简介')),
                ('course_type', models.CharField(max_length=50, verbose_name='课程类型')),
                ('teacher_id', models.CharField(max_length=20, verbose_name='授课教师编号')),
                ('start_time', models.DateTimeField(verbose_name='开课时间')),
                ('end_time', models.DateTimeField(verbose_name='结课时间')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False, verbose_name='成绩编号')),
                ('student_id', models.CharField(max_length=20, verbose_name='学生编号')),
                ('grade', models.FloatField(verbose_name='成绩')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manage.course', verbose_name='课程编号')),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='选课编号')),
                ('teacher_id', models.CharField(max_length=20, verbose_name='授课教师编号')),
                ('student_id', models.CharField(max_length=20, verbose_name='学生编号')),
                ('enrollment_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='选课时间')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manage.course', verbose_name='课程编号')),
            ],
            options={
                'db_table': 'enrollment',
                'unique_together': {('student_id', 'course_id')},
            },
        ),
    ]
