# Generated by Django 5.1.5 on 2025-03-08 10:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('student_id', models.CharField(max_length=20, verbose_name='学生编号')),
                ('content', models.TextField(verbose_name='学习内容')),
                ('duration', models.FloatField(verbose_name='学习时长（分钟）')),
                ('record_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manage.course', verbose_name='课程编号')),
            ],
            options={
                'db_table': 'learning_record',
            },
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, verbose_name='学生编号')),
                ('progress', models.FloatField(default=0.0, verbose_name='学习进度（百分比）')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manage.course', verbose_name='课程编号')),
            ],
            options={
                'db_table': 'learning_progress',
                'unique_together': {('student_id', 'course_id')},
            },
        ),
    ]
