# Generated by Django 5.1.5 on 2025-03-23 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manage', '0003_learningrecord_material_id'),
        ('course_material', '0006_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningrecord',
            name='video_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_material.video', verbose_name='学习视频编号'),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapter_id', models.AutoField(primary_key=True, serialize=False, verbose_name='章节编号')),
                ('chapter_name', models.CharField(max_length=100, verbose_name='章节名称')),
                ('chapter_order', models.IntegerField(verbose_name='章节顺序')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manage.course', verbose_name='课程编号')),
            ],
            options={
                'db_table': 'chapter',
                'ordering': ['chapter_order'],
            },
        ),
    ]
