# Generated by Django 5.1.5 on 2025-03-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manage', '0005_course_total_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningrecord',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='是否完播'),
        ),
    ]
