# Generated by Django 5.1.5 on 2025-04-07 04:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manage', '0007_exam_examrecord_question_option_studentanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='exam_record_id',
        ),
        migrations.RemoveField(
            model_name='option',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='question_id',
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_id']},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_description',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, verbose_name='考试说明'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('midterm', '期中考试'), ('final', '期末考试'), ('quiz', '小测验'), ('custom', '自定义考试')], default='custom', max_length=20, verbose_name='考试类型'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='是否发布'),
        ),
        migrations.AddField(
            model_name='exam',
            name='time_limit',
            field=models.IntegerField(default=60, verbose_name='考试时长(分钟)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_score',
            field=models.IntegerField(default=100, verbose_name='总分'),
        ),
        migrations.AddField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='question',
            name='analysis',
            field=models.TextField(blank=True, null=True, verbose_name='题目解析'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.JSONField(default=dict, verbose_name='正确答案'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], default=1, verbose_name='难度系数'),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, null=True, verbose_name='选项'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manage.course', verbose_name='所属课程'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_time',
            field=models.DateTimeField(verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_time',
            field=models.DateTimeField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manage.exam', verbose_name='所属考试'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', '单选题'), ('multiple_choice', '多选题'), ('true_false', '判断题'), ('fill_blank', '填空题'), ('essay', '问答题')], default='single_choice', max_length=20, verbose_name='题目类型'),
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=1, verbose_name='分值'),
        ),
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='提交编号')),
                ('student_id', models.CharField(max_length=20, verbose_name='学生编号')),
                ('answers', models.JSONField(default=dict, verbose_name='学生答案')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='得分')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('status', models.CharField(choices=[('in_progress', '考试中'), ('submitted', '已提交'), ('graded', '已批改')], default='in_progress', max_length=20, verbose_name='状态')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='教师评语')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manage.exam', verbose_name='所属考试')),
            ],
            options={
                'db_table': 'exam_submission',
                'unique_together': {('exam_id', 'student_id')},
            },
        ),
        migrations.DeleteModel(
            name='ExamRecord',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
    ]
