# Generated by Django 5.1.5 on 2025-02-02 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SysRole",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=30, null=True, verbose_name="角色名称"),
                ),
                (
                    "code",
                    models.CharField(max_length=100, null=True, verbose_name="角色权限字符串"),
                ),
                ("create_time", models.DateField(null=True, verbose_name="创建时间")),
                ("update_time", models.DateField(null=True, verbose_name="更新时间")),
                (
                    "remark",
                    models.CharField(max_length=500, null=True, verbose_name=""),
                ),
            ],
            options={"db_table": "sys_role",},
        ),
        migrations.CreateModel(
            name="SysUserRole",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="role.sysrole"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "sys_user_role",},
        ),
    ]
