# Generated by Django 5.1.5 on 2025-02-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysrole',
            name='code',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='角色权限字符串'),
        ),
    ]
