# Generated by Django 5.1.5 on 2025-02-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女'), (2, '其他')], null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='student_or_teacher_id',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='学生/教师编号'),
        ),
    ]
