# Generated by Django 5.1.5 on 2025-02-24 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('role', '0002_alter_sysrole_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysmenu',
            name='menu_type',
            field=models.CharField(choices=[('M', '目录'), ('C', '菜单'), ('F', '按钮')], max_length=1, null=True, verbose_name='菜单类型'),
        ),
        migrations.AlterField(
            model_name='sysrolemenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='menu.sysmenu', verbose_name='菜单'),
        ),
        migrations.AlterField(
            model_name='sysrolemenu',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menus', to='role.sysrole', verbose_name='角色'),
        ),
    ]
